### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by kelbin** [useless-apple/avito_parser#5]
<img width="668" alt="Снимок экрана 2021-07-03 в 02 50 29" src="https://user-images.githubusercontent.com/28930590/124337074-70998f80-dba9-11eb-9efa-a06abef87905.png">

**Comment by useless-apple** [comment]
@kelbin пришли пожалуйста, ссылку на то, что парсишь.

**Comment by useless-apple** [comment]
@kelbin пофиксил, слил в main
