### ISSUE TITLE
Связь

### ISSUE THREAD

**Issue by kelbin** [useless-apple/avito_parser#7]
Привет, извини, что накатываю тебе ишью, можно ли как-то с тобой связаться для вопросов отдельных? Просто я сделал у себя фиксы, в которые добавил регулярку (чтобы можно было вытаскивать инфу с определенных блоков (могу форк сделать, оно работает)), но при запуске проги прокручивает pages и ничего не происходит. Если есть возможность - было бы клево именно связаться (телеграм, например). Спасибо за понимание.

**Comment by useless-apple** [comment]
Пиши, буду рад помочь
telegram - @useless_apple
